webtalk_init -webtalk_dir C:\\Github\\Zybo_mipi\\Video_Transmission\\Vitis\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-11-02 20:42:54" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vitis v2019.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "Vitis" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "7rhhe6vqs09cd8o77mll5446jm" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.2_46" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "46" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3192 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.198 GB" -context "user_environment"
webtalk_register_client -client vitis
webtalk_add_data -client vitis -key uid -value "1604317217141" -context "vitis\\\\platform/1604317217141"
webtalk_add_data -client vitis -key platform_source -value "dsa" -context "vitis\\\\platform/1604317217141"
webtalk_add_data -client vitis -key os -value "standalone" -context "vitis\\\\platform/1604317217141"
webtalk_add_data -client vitis -key processor -value "ps7_cortexa9" -context "vitis\\\\platform/1604317217141"
webtalk_add_data -client vitis -key platform -value "NA" -context "vitis\\\\platform/1604317217141"
webtalk_transmit -clientid 2419157666 -regid "" -xml C:\\Github\\Zybo_mipi\\Video_Transmission\\Vitis\\webtalk\\usage_statistics_ext_vitis.xml -html C:\\Github\\Zybo_mipi\\Video_Transmission\\Vitis\\webtalk\\usage_statistics_ext_vitis.html -wdm C:\\Github\\Zybo_mipi\\Video_Transmission\\Vitis\\webtalk\\vitis_webtalk.wdm -intro "<H3>Vitis Usage Report</H3><BR>"
webtalk_terminate
