# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Github/Zybo_mipi/zybo_vdma/zybo_vdma.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_1/design_1_mipi_csi2_rx_subsyst_0_1.xci
# IP: The module: 'design_1_mipi_csi2_rx_subsyst_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Github/Zybo_mipi/zybo_vdma/zybo_vdma.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_1/bd_0/bd_11cc.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_11cc || ORIG_REF_NAME==bd_11cc} -quiet] -quiet

# IP: c:/Github/Zybo_mipi/zybo_vdma/zybo_vdma.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_0/bd_11cc_r_sync_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_11cc_r_sync_0 || ORIG_REF_NAME==bd_11cc_r_sync_0} -quiet] -quiet

# IP: c:/Github/Zybo_mipi/zybo_vdma/zybo_vdma.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_1/bd_11cc_rx_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_11cc_rx_0 || ORIG_REF_NAME==bd_11cc_rx_0} -quiet] -quiet

# IP: c:/Github/Zybo_mipi/zybo_vdma/zybo_vdma.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_2/bd_11cc_phy_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_11cc_phy_0 || ORIG_REF_NAME==bd_11cc_phy_0} -quiet] -quiet

# IP: c:/Github/Zybo_mipi/zybo_vdma/zybo_vdma.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_3/bd_11cc_vfb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_11cc_vfb_0_0 || ORIG_REF_NAME==bd_11cc_vfb_0_0} -quiet] -quiet

# XDC: c:/Github/Zybo_mipi/zybo_vdma/zybo_vdma.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_1/bd_0/bd_11cc_ooc.xdc

# XDC: c:/Github/Zybo_mipi/zybo_vdma/zybo_vdma.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_1/design_1_mipi_csi2_rx_subsyst_0_1_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mipi_csi2_rx_subsyst_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Github/Zybo_mipi/zybo_vdma/zybo_vdma.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_1/design_1_mipi_csi2_rx_subsyst_0_1_fixed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mipi_csi2_rx_subsyst_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Github/Zybo_mipi/zybo_vdma/zybo_vdma.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_1/design_1_mipi_csi2_rx_subsyst_0_1.xci
# IP: The module: 'design_1_mipi_csi2_rx_subsyst_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Github/Zybo_mipi/zybo_vdma/zybo_vdma.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_1/bd_0/bd_11cc.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_11cc || ORIG_REF_NAME==bd_11cc} -quiet] -quiet

# IP: c:/Github/Zybo_mipi/zybo_vdma/zybo_vdma.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_0/bd_11cc_r_sync_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_11cc_r_sync_0 || ORIG_REF_NAME==bd_11cc_r_sync_0} -quiet] -quiet

# IP: c:/Github/Zybo_mipi/zybo_vdma/zybo_vdma.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_1/bd_11cc_rx_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_11cc_rx_0 || ORIG_REF_NAME==bd_11cc_rx_0} -quiet] -quiet

# IP: c:/Github/Zybo_mipi/zybo_vdma/zybo_vdma.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_2/bd_11cc_phy_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_11cc_phy_0 || ORIG_REF_NAME==bd_11cc_phy_0} -quiet] -quiet

# IP: c:/Github/Zybo_mipi/zybo_vdma/zybo_vdma.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_3/bd_11cc_vfb_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_11cc_vfb_0_0 || ORIG_REF_NAME==bd_11cc_vfb_0_0} -quiet] -quiet

# XDC: c:/Github/Zybo_mipi/zybo_vdma/zybo_vdma.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_1/bd_0/bd_11cc_ooc.xdc

# XDC: c:/Github/Zybo_mipi/zybo_vdma/zybo_vdma.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_1/design_1_mipi_csi2_rx_subsyst_0_1_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mipi_csi2_rx_subsyst_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Github/Zybo_mipi/zybo_vdma/zybo_vdma.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_1/design_1_mipi_csi2_rx_subsyst_0_1_fixed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mipi_csi2_rx_subsyst_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
